export const videoStyles = {
  '0': {
    elementStyle: {},
    containerStyle: {
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      margin: '5px',
      overflow: `hidden`,
      display: `flex`,
      flexWrap: `wrap`,
      alignItems: `center`,
      justifyContent: `center`,
      outline: `none`,
    },
  },
  '1': {
    elementStyle: {
      position: 'relative',
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      display: 'flex',
      overflow: 'hidden',
      outline: 'none',
      borderRadius: '14px',
      margin: '5px',
    },
    containerStyle: {
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      margin: '5px',
      overflow: `hidden`,
      display: `flex`,
      flexWrap: `wrap`,
      alignItems: `center`,
      justifyContent: `center`,
      outline: `none`,
    },
  },
  '2': {
    elementStyle: {
      position: 'relative',
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      display: 'flex',
      overflow: 'hidden',
      outline: 'none',
      borderRadius: '14px',
      margin: '5px',
    },
    containerStyle: {
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      margin: '5px',
      overflow: 'hidden',
      display: 'grid',
      gridTemplateRows: 'auto auto',
      outline: `none`,
    },
  },
  '3': {
    elementStyle: {
      display: 'flex',
      position: 'relative',
      overflow: 'hidden',
      flexBasis: 'calc(50% - 10px)',
      borderRadius: '14px',
      margin: '5px',
      outline: `none`,
    },
    containerStyle: {
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      overflow: 'hidden',
      display: 'flex',
      justifyContent: 'center',
      margin: '5px',
      alignItems: 'center',
      flexFlow: 'row wrap',
      outline: `none`,
    },
  },
  '4': {
    elementStyle: {
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      position: 'relative',
      display: 'flex',
      overflow: 'hidden',
      outline: 'none',
      borderRadius: '14px',
      margin: '5px',
    },
    containerStyle: {
      margin: '5px',
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      overflow: 'hidden',
      display: 'grid',
      gridTemplateColumns: 'auto auto',
      outline: `none`,
    },
  },
  '5': {
    elementStyle: {
      position: 'relative',
      display: 'flex',
      overflow: 'hidden',
      outline: 'none',
      borderRadius: '14px',
      margin: '5px',
      flexBasis: '33%',
    },
    containerStyle: {
      margin: '5px',
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      overflow: 'hidden',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexFlow: 'row wrap',
      outline: `none`,
    },
  },
  '6': {
    elementStyle: {
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      position: 'relative',
      display: 'flex',
      overflow: 'hidden',
      outline: 'none',
      borderRadius: '14px',
      margin: '5px',
    },
    containerStyle: {
      margin: '5px',
      width: 'calc(100% - 10px)',
      height: 'calc(100% - 10px)',
      overflow: 'hidden',
      display: 'grid',
      gridTemplateColumns: 'auto auto auto',
      outline: `none`,
    },
  },
};
